### PR TITLE
Security Patches, Font/Design Changes, Homepage Hero updates

### PR DESCRIPTION
**Pull request by procifer**
Hi @amarroni,
Can you push this live when you have a chance?  It includes:
- newest Magento security patches
- change layout of Homepage Hero region
- Font and color updates on homepage, nav, etc.
- Add Infinite Scroll plugin for category pages

I have some additional configuration changes I'll need to make on the live site once it's live, so if you could let me know when it's out there, that would be perfect.  Thanks!!

### CODE REVIEW

**Comment by amarroni** [comment]
Josh about the patches applied you double check if all works as expected in
the admin section?.

Ones of the big problem about some of the security patch was changed
default value of allow access for the native core and if you had some
customizacion/3th party extension without the correct ACL configuration,
the admin section will not display for all roles with custom restriction.

I'll push this change tomorrow morning.

Best,
Alejandro.

On Fri, Oct 23, 2015 at 12:15 AM, Josh Smith <notifications@github.com>
wrote:

> Assigned #145 <https://github.com/Topart/new_production/pull/145> to
> @amarroni <https://github.com/amarroni>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Topart/new_production/pull/145#event-443390872>.
>



-- 
*Alejandro Marroni*
Magento Team Leader


<http://www.onetree.com/>

*Uruguay:*
18 de Julio 1077 Piso 10
CP 11100
Montevideo, Uruguay
Ph: (598) 2 908 4138

*www.onetree.com* <http://www.onetree.com/>
*USA:*
5400 Carillon Point
Building 5000, 4th Floor
Kirkland, Washington 98033
Ph: (703) 349 0927*Skype:* alejandro.marroni_ot

**Comment by procifer** [comment]
Hi Alejandro,
Thanks very much!

Yea, I experimented with most of the admin sections and they appeared to be working properly.  Definitely let me know if you see any issues and I can work through them though.

Thanks!
Josh

**Comment by procifer** [comment]
@amarroni, were you able to merge this live?  Thanks!

**Comment by amarroni** [comment]
Hi Josh how are you?,

not ye, as you know for security propoises we don't make any production
update on Friday so was moved for today.  I'll let you know when this
happen.

Best,
Alejandro.

On Mon, Oct 26, 2015 at 2:58 PM, Josh Smith <notifications@github.com>
wrote:

> @amarroni <https://github.com/amarroni>, were you able to merge this
> live? Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Topart/new_production/pull/145#issuecomment-151227524>
> .
>



-- 
*Alejandro Marroni*
Magento Team Leader


<http://www.onetree.com/>

*Uruguay:*
18 de Julio 1077 Piso 10
CP 11100
Montevideo, Uruguay
Ph: (598) 2 908 4138

*www.onetree.com* <http://www.onetree.com/>
*USA:*
5400 Carillon Point
Building 5000, 4th Floor
Kirkland, Washington 98033
Ph: (703) 349 0927*Skype:* alejandro.marroni_ot

**Comment by procifer** [comment]
Ah, gotcha; sorry, wasn’t aware of that.  That sounds great though.  Thanks!

Josh

**Pull request merged**
