### PR TITLE
Style search results page header to match category header

### PR DESCRIPTION
**Pull request by procifer**
@amarroni, for simple changes like this, would it be easier for me to just pull into master myself?  Or would you prefer to review these?  Thanks!

### CODE REVIEW

**Comment by amarroni** [comment]
Josh.

We always need to make the same flow. What ever be the change we must
follow the protocol.

Best,
Alejandro.

On Wednesday, 28 October 2015, Josh Smith <notifications@github.com> wrote:

> Assigned #146 <https://github.com/Topart/new_production/pull/146> to
> @amarroni <https://github.com/amarroni>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Topart/new_production/pull/146#event-448553395>.
>


-- 
*Alejandro Marroni*
Magento Team Leader


<http://www.onetree.com/>

*Uruguay:*
18 de Julio 1077 Piso 10
CP 11100
Montevideo, Uruguay
Ph: (598) 2 908 4138

*www.onetree.com* <http://www.onetree.com/>
*USA:*
5400 Carillon Point
Building 5000, 4th Floor
Kirkland, Washington 98033
Ph: (703) 349 0927*Skype:* alejandro.marroni_ot

**Comment by procifer** [comment]
No worries, just wanted to make sure I’m not being annoying ☺  Thanks for merging all these for me.

Thanks,
Josh

**Comment by procifer** [comment]
@amarroni , will you have a chance to merge this and ship live soon?  Sorry to bug you; just let me know when you're thinking.  Thanks!

**Comment by amarroni** [comment]
Merge complete,
@procifer I saw some styles inline, that kind of thing is not so good as we run a responsive site. Next time you want to add something new create a new branch based on last master.

Best,
Alejandro.

**Comment by procifer** [comment]
Thanks Alejandro!  Will do.

Josh

Sent from Outlook<http://aka.ms/Ox5hz3>

_____________________________

**Pull request merged**
