### PR TITLE
Replace icons at bottom of product page with new styled assets

### PR DESCRIPTION
**Pull request by procifer**
@amarroni , just small update to change the icons at bottom of product page.  Thanks!

### CODE REVIEW

**Comment by amarroni** [comment]
Hi Josh how are you?,

As you know Friday we not push anything to production site, that push will
be made Monday first time in the morning.

Best,
Alejandro.

On Thu, Dec 3, 2015 at 7:12 PM, Josh Smith <notifications@github.com> wrote:

> Assigned #151 <https://github.com/Topart/new_production/pull/151> to
> @amarroni <https://github.com/amarroni>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Topart/new_production/pull/151#event-482016681>.
>



-- 
*Alejandro Marroni*
Magento Team Leader


<http://www.onetree.com/>

*Uruguay:*
18 de Julio 1077 Piso 10
CP 11100
Montevideo, Uruguay
Ph: (598) 2 908 4138

*www.onetree.com* <http://www.onetree.com/>
*USA:*
5400 Carillon Point
Building 5000, 4th Floor
Kirkland, Washington 98033
Ph: (703) 349 0927*Skype:* alejandro.marroni_ot

**Comment by procifer** [comment]
No worries – Monday would be great.  Thanks Alejandro!

Josh

**Comment by procifer** [comment]
Actually this one is superceded by the #152

**Comment by amarroni** [comment]
Good morning Josh,

I'll pushing to production after lunch.

Let me know if you need anything else.

Best,
Alejandro.

On Fri, Dec 4, 2015 at 11:40 PM, Josh Smith <notifications@github.com>
wrote:

> Actually this one is superceded by the #152
> <https://github.com/Topart/new_production/pull/152>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Topart/new_production/pull/151#issuecomment-162133541>
> .
>



-- 
*Alejandro Marroni*
Magento Team Leader


<http://www.onetree.com/>

*Uruguay:*
18 de Julio 1077 Piso 10
CP 11100
Montevideo, Uruguay
Ph: (598) 2 908 4138

*www.onetree.com* <http://www.onetree.com/>
*USA:*
5400 Carillon Point
Building 5000, 4th Floor
Kirkland, Washington 98033
Ph: (703) 349 0927*Skype:* alejandro.marroni_ot

**Pull request closed without merging**
